<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Remote Debug</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^(.*)(error|Error|ERROR)(.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.remotebuild</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.remotebuild</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(D)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>comment.remotebuild</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>comment.remotebuild</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^(.*)(warning|Warning|WARNING)(.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild.timestamp</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.remotebuild</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>keyword.remotebuild</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^([\d\- :.]*)(.)\/(.*)\( *(\d+)\): (.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild.timestamp</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.remotebuild</string>
                </dict>
            </dict>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.remotebuild</string>
    <key>uuid</key>
    <string>59F39BAA-EBD3-468A-9965-2C47C3B30C11</string>
</dict>
</plist>
